server:
  port: 9999

# spring配置
spring:
  profiles:
    # 环境 dev|test|prod
    active: dev

  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        #naocs-server地址
        server-addr: ${nacos.discovery.server-addr}
      config:
        # 配置中心地址
        server-addr: ${nacos.config.server-addr}
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml

# 自定义配置
app:
  # 跨域配置是否开启
  cors:
    enabled: true