server:
  port: 80

# mysql
spring:
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.230.7:3306/mall_product?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mh.123456

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis Plus
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml

