server:
  port: 18081
  servlet:
    context-path: /

spring:
  application:
    name: mall-auth
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${admin-db.url}
    username: ${admin-db.username}
    password: ${admin-db.password}