server:
  port: 18082
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        #naocs-server地址
        server-addr: http://192.168.230.7:8848

minio:
  url: http://192.168.230.7:9000
  name: cqgsl
  pass: gsl_123456
  bucketName: gongshanglian